version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ~/.m2:/root/.m2
    expose:
      - 8080
    depends_on:
      - mysql
    command: mvn spring-boot:run -Dspring-boot.run.profiles=docker

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
