spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

cache:
  config:
    entryTtl: 60
    countryNames:
      entryTtl: 30